version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - npm install
      - npm install -g allure-commandline
  build:
    commands:
      - npm run all
