version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest

  pre_build:
    commands:
      - yum install -y xorg-x11-server-Xvfb gtk2-devel gtk3-devel libnotify-devel GConf2 nss libXScrnSaver alsa-lib
      - npm install
      - npm install -g allure-commandline
  build:
    commands:
      - npm run ci
  post_build:
    commands:
       - aws s3 sync allure-report s3://testreportbucketrrenjifo/
       - aws s3 cp --acl public-read s3://testreportbucketrrenjifo/ s3://testreportbucketrrenjifo/ --recursive --metadata-directive REPLACE